[options]
automatic_update = true
buffer_index_type = 4
colorscheme = 'onedark'
colorscheme_bg = 'dark'
default_indent = 4
enable_filetree_gitstatus = true
# enable_guicolors = true
enable_projects_cache = true
enable_statusline_mode = true
enable_tabline_filetype_icon = true
expand_tab = false
filemanager = 'nerdtree'
guifont = "Mono Lisa Mono:h11"
filetree_direction = 'left'
project_non_root = ''
project_rooter_outermost = false
project_rooter_patterns = [
  '.git/',
  '_darcs/',
  '.hg/',
  '.bzr/',
  '.svn/',
  '!node_packages/',
  '!node_modules/',
  '!bower_components/',
  '!vendor/',
  '!build/',
  '!dist/',
  '!tmp/',
  '!log/',
  '!logs/',
  '!coverage/',
  '!target/',
]
projects_cache_num = 20
statusline_iseparator = "slant"
statusline_separator = "slant"

[[custom_plugins]]
merged = false
repo = 'https://github.com/joshdick/onedark.vim'

[[custom_plugins]]
merged = false
repo = 'https://github.com/rmehri01/onenord.nvim'

[[layers]]
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"
name = 'autocomplete'

[[layers]]
default_height = 30
default_position = 'bottom'
name = 'shell'

[[custom_plugins]]
merged = false
repo = "lilydjwg/colorizer"

[[custom_plugins]]
merged = false
repo = "wakatime/vim-wakatime"

[[layer]]
name = 'colorscheme'

[[layers]]
enable_scrollbar = true
name = "ui"
